# Site settings
title: Kyle's Blog
email: kylethompson86@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mostly gibberish.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kylethompson.co.uk" # the base hostname & protocol for your site
twitter_username: kylethompson86
github_username:  kylethompson

# Build settings
markdown: kramdown